/***

  Pinup JavaScript
  http://www.jbull.ca/work/pinup
  @copyright: Copyright (c) 2012 Pinup. All rights reserved.
  @license: Dual licensed under the MIT or GPL Version 2 licenses.
  @version: 2.02-minimal-live
  @date: 2012-12-18

***/
(function(n){var N,Y,Z,$,aa,ba,ca,T,da,ea,fa,ga;function ha(a){this.scope=a;this.allowPrivateInterfaces=this.isHidden=this.hasUi=!1;this.offsetRight=this.offsetLeft=0;this.leftNavItems=[{className:g.btnAddnew,label:"ADD NEW TAG",isPrivate:!0,event:function(a,d){var e=function(){0===w[t.user.tagTotal]?f.openWindow(z.msgFirstTag,function(){b.click(b.getElementsByClassName(g.formBtnSubmit,this)[0],function(){f.closeWindow();a.scope.startTaggingMode(a.scope.methodAddNewTag)})}):a.scope.startTaggingMode(a.scope.methodAddNewTag)};
f.waitButton(d,x.leftNavWait);f.checkLogin(e,function(){f.promptLogin(e)},function(){f.unwaitButton(d)})}}]}function ia(a,c){this.uid=c;this.image=a;this.imageSrc=b.attribute(a,j.altImageSrc)||a.src;this.imageClone=a.cloneNode(!0);this.disallowNodeUpdate=!1;this.allowTagBubble=!0;this.privateElements={};this.settings={};this.dimensions={width:a.width,height:a.height,offsetLeft:D[c].offset.x,offsetTop:D[c].offset.y};this.updateInProgress=!1}function ja(a,c){if(n===this)return new ja(a,c);j=b.cloneObject(P);
c&&f.updateSettings(c);f.updateWindowNamespace();b.onDomReady(function(){var d,e=s.checkSite+p.publicKey,B=function(a){a&&f.updateSettings(a);c&&f.updateSettings(c);f.systemStart()};ka||(ka=!0,a&&(p.publicKey=a),(d=f.getLocalStorage(e))?B(d):b.isUndefined(p.publicKey)||b.loadJSONP(r.names.checkSite,{strWebUrl:n.location.hostname},function(a){null!==a&&(B(a),f.setLocalStorage(e,a))}),b.addEvent(n,k.unload,f.systemStop))})}var ka=!1,L=!1,p={},m={},A={},D={},H={},I={},G={},u={},Q={},K={},R={},S={},w=
{},la,O=!1,v={},J={},U,V,W,b,f,P,j,g,r,x,k,h,z,t,l=n.document,ra=Object.prototype.toString,ma=n.location.href,na=l.defaultView,oa=["http://","https://"],X=oa[0],s={root:"Pinup",json:"jsonpHandler",globalVars:"globalVars",settings:"settings",defaultSettings:"defaultSettings",user:"user",lib:"lib",fn:"fn",images:"images",nodes:"nodes",tags:"tags",events:"events",elements:"elements",checkSite:"checkSite-",checkImage:"checkImage-",vmlCanvas:"G_vmlCanvasManager"},pa={1:"yes","0":"no"},M=0,qa;r={names:{getTags:"get_tags",
getTagSugg:"get_tag_suggestion",register:"register",login:"login",logout:"logout",forgot:"forgot_pass",checkLogin:"check_login",checkImage:"check_image",checkSite:"get_site_settings",tagCreate:"tag_create",tagPosition:"tag_position",tagRemove:"tag_remove",logTagHover:"log_tag_hover"},paths:{twitter:"http://twitter.com/intent/tweet?",facebook:"https://www.facebook.com/sharer.php?",gateway:"http://www.jbull.ca/work/pinup/gateway/",cdn:"http://www.jbull.ca/work/pinup/cdn/",website:"http://www.jbull.ca/work/pinup/"}};
r.paths.webloc=r.paths.gateway+"webloc.php?u=";r.paths.hub=r.paths.gateway+"hub.php";r.paths.themes=r.paths.cdn+"frontend-themes/css/";r.paths.excanvas=r.paths.cdn+"global-js/excanvas.js";P={nMinWidth:250,nMinHeight:200,jsonpTimeout:3E4,scrollDelay:300,navAniSpeed:250,loadImages:[],loadAll:!1,smartLoad:!0,forceListen:!1,alwaysShowTags:!0,cssHelper:!0,posHelper:!0,animations:!0,keyListener:!0,onReady:function(){},onLogout:function(){},onLogin:function(){},themeFile:"",allowFile:"jpg|jpeg|png",allowThemeManager:!1,
allowLocalStorage:!1,allowBottomLinks:!1,allowShare:!0,dotSize:"medium",dotOutlineSize:6,canvas:{cornerRadius:5,tailWidth:19,tailHeight:8,stroke:!1,shadow:!0,theme:{backgroundStyle:"radial",backgroundColor:"0-#FFFFFF 1-#CCCCCC",strokeWidth:1,strokeColor:"#000000",shadowOffsetX:0,shadowOffsetY:0,shadowBlur:5,shadowColor:"#000000"}},tooltip:!0,tooltipOrientation:"top",tooltipURL:!0,altImageSrc:"pinsrc",activeParentClass:"allpins",activeChildClass:"pinimg",custom:{}};g={docBody:"PIN_active",noAnimation:"PIN_noAnimation",
noRgbaSupport:"PIN_noRgbaSupport",noBoxShadowSupport:"PIN_noBoxShadowSupport",noBorderRadiusSupport:"PIN_noBorderRadiusSupport",wrapper:"PIN_wrapper",lightbox:"PIN_lightbox",lightboxWindow:"PIN_lightboxWindow",lightboxOverlay:"PIN_lightboxOverlay",lightboxImage:"PIN_lightboxImage",lightboxImageHolder:"PIN_lightboxImageHolder",lightboxNav:"PIN_lightboxNav",lightboxShowLeft:"PIN_lightboxShowLeft",lightboxShowRight:"PIN_lightboxShowRight",lightboxNavIcon:"PIN_lightboxNavIcon",node:"PIN_node",inlineNode:"PIN_inlineNode",
sectionBody:"PIN_sectionBody",sectionFooter:"PIN_sectionFooter",image:"PIN_image",overlay:"PIN_overlay",logo:"PIN_logo",button:"PIN_button",lastItem:"PIN_lastItem",noSelect:"PIN_noSelect",handOver:"PIN_handOver",handDrag:"PIN_handDrag",iconLabel:"PIN_iconLabel",guiLeftHolder:"PIN_guiLeftHolder",guiRightHolder:"PIN_guiRightHolder",guiBotL:"PIN_btnBotL",guiTopR:"PIN_btnTopR",btnCancel:"PIN_btnCancel",btnSettings:"PIN_btnSettings",btnAddnew:"PIN_btnAddTag",window:"PIN_window",windowOverlay:"PIN_windowOverlay",
windowBackground:"PIN_windowBackground",windowClose:"PIN_windowBtnClose",windowBody:"PIN_windowBody",windowLogout:"PIN_windowLogout",windowUserName:"PIN_windowUserName",windowHeader:"PIN_header",windowTitle:"PIN_title",prompt:"PIN_prompt",promptMessage:"PIN_promptMessage",promptAccept:"PIN_promptAccept",promptDeny:"PIN_promptDeny",modalMsg:"PIN_modalMsg",focus:"PIN_focus",formStyle:"PIN_formStyle",formError:"PIN_formError",formDisabledMsg:"PIN_formDisabledMsg",formErrorRow:"PIN_formErrorRow",formLabel:"PIN_formLabel",
formLabelSm:"PIN_formLabel-sm",formTextField:"PIN_textField",formTextArea:"PIN_textArea",formDropDown:"PIN_dropDown",formDropDownDiv:"PIN_dropDownDiv",formBtnSubmit:"PIN_formBtnSubmit",formBtnLeft:"PIN_formBtnLeft",formOptions:"PIN_options",formOption_forgotPass:"PIN_optForgotPass",formOption_backToLogin:"PIN_optBackToLogin",formOption_register:"PIN_optRegister",tag:"PIN_tag",tagSmall:"PIN_tagSmall",tagMedium:"PIN_tagMedium",tagLarge:"PIN_tagLarge",tagHolder:"PIN_tagHolder",tagDot:"PIN_tagDot",tagOutline:"PIN_tagOutline",
tagBubble:"PIN_tagBubble",tagBubbleContent:"PIN_tagBubbleContent",tagBubbleCanvas:"PIN_tagBubbleCanvas",tagBubbleButton:"PIN_tagBubbleButton",tagLink:"PIN_tagLink",tagLinkText:"PIN_tagLinkText",tagLinkURL:"PIN_tagLinkURL",tagLinkLike:"PIN_tagLinkLike",tagDirLeft:"PIN_tagDirL",tagDirRight:"PIN_tagDirR",link:"PIN_link",linkHolder:"PIN_linkHolder",linkHolderBackground:"PIN_linkHolderBackground",linkPending:"PIN_linkPending",shareHolder:"PIN_shareHolder",shareHeader:"PIN_shareHeader",shareButtons:"PIN_shareButtons",
shareButton:"PIN_shareButton",actionOn:"PIN_on",actionShowWin:"PIN_showWin",taggingMode:"PIN_taggingMode",repositionMode:"PIN_repositionMode",removalMode:"PIN_removalMode"};x={noResults:"No results found.",loading:"Loading...",leftNavWait:"THINKING...",formWait:"PLEASE WAIT...",removeTag:"Are you sure you wish to permanently delete this tag?",removeMultiTags:"Are you sure you wish to permanently delete this tag? Caution: There are multiple links associated with this tag.",missingReqInput:"A REQUIRED FIELD IS EMPTY",
invalidEmail:"EMAIL ADDRESS IS NOT VALID"};k={submit:"submit",scroll:"scroll",click:"click",load:"load",unload:"unload",keyup:"keyup",focus:"focus",blur:"blur",change:"change",mouseover:"mouseover",mouseout:"mouseout",mousedown:"mousedown",mouseup:"mouseup",mousemove:"mousemove",selectstart:"selectstart",readystatechange:"readystatechange",domcontentloaded:"domcontentloaded"};N="img";t={user:{guid:"guid",tagTotal:"tagTotal",fullName:"fullName",isOwner:"isOwner"},tags:{guid:"strGUID",name:"strTagName",
imagePath:"strImageURL",posX:"nPosX",posY:"nPosY",keywords:"arrKeywords",webLink:"strWebLink",ownerGuid:"nTaggerAccountsID"}};Y=/[\s,]+/;Z=/\s/g;$=/^\s\s*/;aa=/\s\s*$/;ba=/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*):?([^:@]*))?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/;ca=/(?:^|&)([^&=]*)=?([^&]*)/g;T=/[^0-9\.\-]+/g;da=/-+(.) ?/g;ea=/\/$/g;fa=/[^.]+$/;ga=/^0.55$/;p.availableThemes={"default":825248,launch:469725,virgin:979253};p.availableDotSizes={small:g.tagSmall,
medium:g.tagMedium,large:g.tagLarge};p.tooltipOrientations={top:"top",right:"right",bottom:"bottom",left:"left"};p.canvasDrawStyles={radial:"radial",linear:"linear",solid:"solid"};b={onDomReady:function(a){var c=l.addEventListener?k.domcontentloaded:k.readystatechange,d=function(){b.removeEvent(l,c);b.removeEvent(n,k.load)};"complete"!==l.readyState?(b.addEvent(l,c,function(){"complete"===l.readyState&&(d.call(),a.call())}),b.addEvent(n,k.load,function(){d.call();a.call()})):a.call()},loadScript:function(a,
c){var d,e={},B=function(){b.removeEvent(d,k.readystatechange);b.removeEvent(d,k.load)};e.src=a;e.type="text/javascript";d=b.domAppend("script",l.getElementsByTagName("head")[0],e);b.addEvent(d,k.readystatechange,function(){if("complete"===d.readyState||"loaded"===d.readyState)B.call(),c(d)});b.addEvent(d,k.load,function(){B.call();c(d)})},type:function(a){switch(a){case null:return"null";case void 0:return"undefined"}switch(ra.call(a)){case "[object Boolean]":return"boolean";case "[object Number]":return"number";
case "[object String]":return"string";case "[object Array]":return"array";case "[object Function]":return"function";case "[object Date]":return"date"}return 1===a.nodeType?"element":"object"},isElement:function(a){return"element"===b.type(a)},isNull:function(a){return"null"===b.type(a)},isUndefined:function(a){return"undefined"===b.type(a)},isBoolean:function(a){return"boolean"===b.type(a)},isNumber:function(a){return"number"===b.type(a)},isString:function(a){return"string"===b.type(a)},isObject:function(a){return"object"===
b.type(a)},isFunction:function(a){return"function"===b.type(a)},isArray:function(a){return"array"===b.type(a)},isNumeric:function(a){return!isNaN(parseFloat(a))&&isFinite(a)},hasClass:function(a,c){return RegExp("\\b"+c+"\\b").test(a.className)},addClass:function(a,c){b.hasClass(a,c)||(a.className+=a.className?" "+c:c)},removeClass:function(a,c){var b=a.className.match(" "+c)?" "+c:c;a.className=a.className.replace(b,"")},getParentByClassName:function(a,c){for(;a&&!b.hasClass(a,c);)a=a.parentNode||
null;return a},getElementsByClassName:function(a,c){var d=[];c=c||l.getElementsByTagName("body").item(0);b.loopArray(c.getElementsByTagName("*"),function(c){b.hasClass(c,a)&&d.push(c)});return d},hasProperty:function(a,c){var d=Object.prototype.hasOwnProperty,e="__proto__";if(d)return d.call(a,c);e=a[e]||a.constructor.prototype;return!b.isUndefined(a[c])&&(b.isUndefined(e[c])||e[c]!==a[c])},loop:function(a,c){for(var b=0;b<a&&null!==c(b);)b++},rloop:function(a,c){for(;a--;)c(a)},loopArray:function(a,
c){b.loop(a.length,function(b){return 2===c.length?c(b,a[b]):c(a[b])})},loopObject:function(a,b){for(var d in a)if(1===b.length){if(null===b(a[d]))break}else if(2===b.length&&null===b(d,a[d]))break},loopObjectKeys:function(a,b){for(var d in a)if(null===b(d))break},isObjectEmpty:function(a){for(var c in a)if(b.hasProperty(a,c))return!1;return!0},mergeObject:function(a,b){for(var d in b)a[d]=b[d];return a},cloneObject:function(a){var c={};if(!b.isObject(a))return a;b.loopObject(a,function(a,e){c[a]=
b.cloneObject(e)});return c},getParamsFromObject:function(a){var c=[];b.loopObject(a,function(a,b){c[c.length]=encodeURIComponent(a)+"="+encodeURIComponent(b)});return c.join("&")},getEventTarget:function(a){a=a||n.event;a=a.target||a.srcElement;3===a.nodeType&&(a=a.parentNode);return a},randomID:function(a){for(var b="",d=0;d<a;)b+="0123456789ABCDEFGHIJKLMNOPQURSTUVWXYZ".substr(Math.floor(37*Math.random()),1),d++;return b},getMousePosition:function(a){a=a||n.event;var b=l.documentElement,d=l.body,
e={x:0,y:0};a.pageX||a.pageY?(e.x=a.pageX,e.y=a.pageY):(e.x=a.clientX+(b.scrollLeft||d.scrollLeft)-b.clientLeft,e.y=a.clientY+(b.scrollTop||d.scrollTop)-b.clientTop);return e},getWidth:function(a){var c=a.offsetWidth||a.clientWidth;c||(b.setStyle(a,"visibility","hidden"),b.show(a),c=a.offsetWidth||a.clientWidth,b.hide(a),b.setStyle(a,"visibility","visible"));return c||0},setWidth:function(a,c){b.setStyle(a,"width",c)},getHeight:function(a){var c=a.offsetHeight||a.clientHeight;c||(b.setStyle(a,"visibility",
"hidden"),b.show(a),c=a.offsetHeight||a.clientHeight,b.hide(a),b.setStyle(a,"visibility","visible"));return c||0},setHeight:function(a,c){b.setStyle(a,"height",c)},getCumulativeOffset:function(a){var b={x:0,y:0};if(a.offsetParent){do b.x+=a.offsetLeft,b.y+=a.offsetTop,a=a.offsetParent;while(a)}return b},attribute:function(a,c,d){var e=a.nodeType;if(a&&!(3===e||8===e||2===e))if(b.isObject(c))b.loopObject(c,function(c,d){b.attribute(a,c,d)});else{if(b.isUndefined(d))return a.getAttribute(c);if(null===
d||!1===d)"class"===c?b.removeClass(a,d):a.removeAttribute(c);else return"class"===c?b.addClass(a,d):a.setAttribute(c,d),d}},getGUID:function(a){var c;a===n?c="GUID-window":a===l?c="GUID-document":(c=b.attribute(a,"guid"))||(c=b.attribute(a,"guid",b.randomID(16)));return c},setStyles:function(a,c){b.loopObject(c,function(c,e){b.setStyle(a,c,e)})},setStyle:function(a,c,d){var e=a.style;c="float"===c?v.cssFloat:c;if(e&&a&&!(3===a.nodeType||8===a.nodeType))"opacity"===c?b.setAlpha(a,d):(b.isNumber(d)&&
!b.inArray(["zIndex","opacity"],c)&&(d+="px"),f.attempt(function(){e[c]=d}))},getStyle:function(a,c,d){b.isString(a)&&(d=c,c=a,a=void 0);"opacity"===c&&!v.opacity?a=(a=b.getStyle(a,"filter",d))?parseFloat(a.replace(T,""))/100:null:(d=d||b.getComputedStyles(a),a=d[c]);return"auto"===a?null:a},getComputedStyles:function(a){var c={},d=na?na.getComputedStyle(a,null):a.currentStyle;a=d.length;var e=function(a){var e,f;b.isUndefined(d.getPropertyValue)||(e=d.getPropertyValue(a));e||(e=d[a]);if(e){f=b.type(e);
if(b.isNumeric(e)&&"number"!==f||"string"===f&&0<e.indexOf("px"))f=parseFloat(e),isNaN(f)||(e=f);c[b.camelize(a)]=e}};a?b.loop(a,function(a){e(d[a])}):b.loopObjectKeys(d,function(a){b.hasProperty(d,a)&&e(a)});return c},camelize:function(a){return a.replace(da,function(a,b){return b?b.toUpperCase():""})},stopBubble:function(a){a=a||n.event;a.preventDefault?a.preventDefault():a.returnValue=!1;a.stopPropagation?a.stopPropagation():a.cancelBubble=!0},removeChildren:function(a){if(a)for(;a.hasChildNodes();)b.removeElement(a.firstChild)},
cleanElement:function(a){var c=b.getGUID(a);b.removeAllEvents(a);b.removeChildren(a);f.removeAllKeyListeners(c);delete Q[c]},removeElement:function(a){a&&(b.cleanElement(a),a.parentNode&&a.parentNode.removeChild(a))},replaceElement:function(a,c){b.cleanElement(a);b.isString(c)&&(c=l.createTextNode(c));a.parentNode&&a.parentNode.replaceChild(c,a)},insertBefore:function(a,b){a.parentNode.insertBefore(b,a);return b},insertAfter:function(a,c){b.isString(c)&&(c=l.createTextNode(c));a.parentNode.insertBefore(c,
b.getNextSibling(a));return c},getNextSibling:function(a){do a=a.nextSibling;while(a&&1!==a.nodeType);return a},newElement:function(a,c,d){a=l.createElement(a);var e=b.getGUID(a);Q[e]=a;c&&b.isString(c)&&(d=d||c,c={});c&&b.isObject(c)&&b.attribute(a,c);d&&b.isString(d)&&b.appendText(a,d);return a},domAppend:function(a,c,d,e){d&&b.isString(d)&&(e=e||d,d={});b.isString(a)&&(a=b.newElement(a,d,e));d=a.nodeType;e=c.nodeType;(1===d||11===d||3===d)&&(1===e||11===e||3===e)&&c.appendChild(a);return a},domWrap:function(a,
c,d,e){d&&b.isString(d)&&(e=e||d,d={});b.isString(a)&&(a=b.newElement(a,d,e));b.isElement(a)&&b.isElement(c)&&(c.parentNode.insertBefore(a,c),b.domAppend(c,a));return a},isElementIn:function(a,b){for(;a;){if(a===b||a.nodeName.toLowerCase()===b)return!0;a=a.parentNode}return!1},isElementEmpty:function(a){return 0===a.children.length},parseHTML:function(a,c){var d=l.createDocumentFragment(),e;e=function(a){var d={},f;b.hasProperty(a,c.id)&&(d.id=a[c.id]);b.hasProperty(a,c.className)&&(d["class"]=a[c.className]);
b.hasProperty(a,c.attr)&&b.loopObject(a[c.attr],function(a,b){d[a]=b});b.hasProperty(a,c.nodeName)&&(f=b.newElement(a[c.nodeName],d),a[c.childNodes]&&0<a[c.childNodes].length&&b.loopArray(a[c.childNodes],function(a){b.domAppend(e(a),f)}));a[c.text]&&0<a[c.text].length&&(f?b.appendText(f,a[c.text]):f=l.createTextNode(a[c.text]));return f};c=c||{nodeName:"nodeName",childNodes:"childNodes",className:"className",id:"id",attr:"attr",text:"text"};b.isArray(a)?b.loopArray(a,function(a){b.domAppend(e(a),
d)}):b.isObject(a)&&b.domAppend(e(a),d);return d},replaceHTML:function(a,c){b.removeChildren(a);b.isString(c)?b.appendText(a,c):a.appendChild(b.parseHTML(c))},appendText:function(a,b){if(0<b.length)return a.appendChild(l.createTextNode(b))},textContentRecursive:function(a,c){for(;a;){if(!a.firstChild||!b.isElement(a.firstChild))return c?b.textContent(a,c):b.textContent(a);a=a.firstChild}},textContent:function(a,c){var d,e,f;d=0;for(e=a.childNodes.length;d<e;d++)if(f=a.childNodes[d],3===f.nodeType)return c&&
(f.nodeValue=c),f.nodeValue;return c?b.appendText(a,c):""},disableSelection:function(a){b.isUndefined(a.onselectstart)||(a.onselectstart=function(){return!1});b.addClass(a,g.noSelect);b.attribute(a,"unselectable","on")},show:function(a){a.style.display="block"},hide:function(a){a.style.display="none"},isVisible:function(a){a=b.getComputedStyles(a);return!("hidden"===b.getStyle("visibility",a)||"none"===b.getStyle("display",a)||0===b.getStyle("opacity",a))},handleEvent:function(a){a=a||n.event;b.stopBubble(a);
var c=this,d=!0,e=c.events[a.type];b.loopObjectKeys(e,function(b){c.handleEvent=e[b];!1===c.handleEvent(a)&&(d=!1)});return d},hasEvent:function(a,c){var d=b.getGUID(a);return!(!u[d]||!u[d][c])},addEvent:function(a,c,d){var e=b.getGUID(a);b.hasEvent(a,c)||(u[e]||(u[e]={}),u[e][c]={element:a,handler:d},a.addEventListener?a.addEventListener(c,d,!1):(d.guid||(d.guid=b.randomID(12)),a.events||(a.events={}),e=a.events[c],e||(e=a.events[c]={},a["on"+c]&&(e[0]=a["on"+c])),e[d.guid]=d,a["on"+c]=b.handleEvent))},
removeEvent:function(a,c){var d=b.getGUID(a),e;b.hasEvent(a,c)&&(e=u[d][c].handler,delete u[d][c],b.isObjectEmpty(u[d])&&delete u[d],a.removeEventListener?a.removeEventListener(c,e,!1):a.events&&a.events[c]&&delete a.events[c][e.guid])},removeAllEvents:function(a){var c=b.getGUID(a);u[c]&&b.loopObjectKeys(u[c],function(c){b.removeEvent(a,c)})},fireEvent:function(a,c){var d;b.hasEvent(a,c)&&(l.createEvent?(d=l.createEvent("HTMLEvents"),d.initEvent(c,!0,!0),a.dispatchEvent(d)):(d=l.createEventObject(),
d.eventType="on"+c,a.fireEvent(d.eventType,d)))},click:function(a,c,d){d=d||!1;c&&b.addClass(a,g.button);b.addEvent(a,k.click,function(e){b.stopBubble(e);d&&(b.removeEvent(a,k.click),b.removeClass(a,g.button));c&&c.call(a,e);return!1})},jsonpGarbageCollect:function(a){b.removeElement(l.getElementById(a));clearTimeout(S[a]);delete S[a];delete R[a]},loadJSONP:function(a,c,d){var e="JSONP_"+b.randomID(12),f="",g=(new Date).getTime();c&&(b.isFunction(c)?(d=c,c=""):b.isObject(c)&&(f=(f=b.getParamsFromObject(c))?
"&"+f:""));a=r.paths.hub+"?r="+a+"&jsid="+e+"&pk="+p.publicKey+f;0<j.jsonpTimeout&&(S[e]=setTimeout(function(){d&&d(null,j.jsonpTimeout);b.jsonpGarbageCollect(e)},j.jsonpTimeout));R[e]=function(a){var c=(new Date).getTime()-g;d&&d(a,c);b.jsonpGarbageCollect(e)};b.domAppend("script",l.getElementsByTagName("head").item(0),{id:e,src:a,type:"text/javascript"})},stopAnimation:function(a){a.animationMemory&&clearInterval(a.animationMemory)},animate:function(a,c,d,e,f){var g=[],E,j=(new Date).getTime(),
h=function(c,d){var e={};e.cssProp=c;e.startValue=b.getStyle(a,e.cssProp)||0;e.endValue=d;e.displacement=e.endValue-e.startValue;!isNaN(e.startValue)&&(!isNaN(e.endValue)&&!isNaN(e.displacement))&&g.push(e)};b.isObject(c)?(f=e,e=d,d=null,b.loopObject(c,function(a,b){h(a,b)})):h(c,d);0!==g.length&&(E=Math.PI/(2*e),a.animationMemory&&b.stopAnimation(a),a.animationMemory=setInterval(function(){var c=(new Date).getTime()-j,d=Math.abs(Math.sin(c*E));c<e?b.loopArray(g,function(c){b.setStyle(a,c.cssProp,
d*c.displacement+c.startValue)}):(b.stopAnimation(a),b.loopArray(g,function(c){b.setStyle(a,c.cssProp,c.endValue)}),f&&f.call(a))},10))},setAlpha:function(a,b){v.opacity?a.style.opacity=b:a.style.filter="alpha(opacity = "+String(100*b)+") "},fadeTo:function(a,c,d,e){b.animate(a,"opacity",c,d,e)},fadeIn:function(a,c,d){b.fadeTo(a,1,c,d)},fadeOut:function(a,c,d){b.fadeTo(a,0,c,d)},stripSpaces:function(a){return a.replace(Z,"")},inArray:function(a,c){var d=!1;b.loopArray(a,function(a){if(a===c)return d=
!0,null});return d},arrayUnique:function(a){var c=[];b.loopArray(a,function(a){b.inArray(c,a)||(c[c.length]=a)});return c},removeArrayItem:function(a,c){b.loopArray(a,function(b,e){e===c&&a.splice(b,1)});return a},parseUrl:function(a){var b="source protocol authority userInfo user password host port relative path directory file query anchor".split(" ");a=ba.exec(a);for(var d={},e=14;e--;)d[b[e]]=a[e]||"";d.queryKey={};d[b[12]].replace(ca,function(a,b,c){b&&(d.queryKey[b]=c)});return d},getFileExtension:function(a){return(a=
(a=a?b.parseUrl(a).file:null)?fa.exec(a).pop():null)?a.toLowerCase():null},runInterval:function(a,b,d,e,f){var g,E=0;!0===d.call()?e.call():g=n.setInterval(function(){!0===d.call()?(clearInterval(g),e.call()):(E++,E>=b&&(n.clearInterval(g),f&&f.call()))},a)},stringFormat:function(a,c){var d=a;b.loopArray(c,function(a,b){d=d.replace(RegExp("\\{"+a+"\\}","gi"),b)});return d}};h={buildForm:function(a,c,d){var e={};c=[{nodeName:"div",className:g.formError}].concat(c);b.isUndefined(d)||(c=c.concat([h.buildButton(d)]));
e.name=a;return[{nodeName:"form",id:a,className:g.formStyle,attr:e,childNodes:c}]},buildFormInput:function(a,b){return{nodeName:"input",attr:{type:a,name:b,autocomplete:"off"}}},buildFormTextArea:function(a){return{nodeName:"textarea",attr:{name:a}}},buildFormSelect:function(a,c){var d=[];b.loopObject(c,function(a,b){d.push({nodeName:"option",attr:{value:a},text:b})});return{nodeName:"select",attr:{name:a},childNodes:d}},buildFormLabelSm:function(a,b){return h.buildFormLabel(a,b,!0)},buildFormLabel:function(a,
b,d){var e={};d=d?g.formLabelSm:g.formLabel;e.input=g.formTextField;e.textarea=g.formTextArea;e.select=g.formDropDown;return{nodeName:"label",className:d+" "+e[b.nodeName],text:a+": ",childNodes:[{nodeName:"span",childNodes:[b]}]}},buildHeader:function(a){return{nodeName:"div",className:g.windowHeader,childNodes:[{nodeName:"a",className:g.logo,text:"Pinup",attr:{href:r.paths.website}},{nodeName:"h2",className:g.windowTitle,text:a}]}},buildButton:function(a,c){var d=g.formBtnSubmit,e={type:"button"};
c&&(b.isFunction(c)&&(c=c.call()),b.hasProperty(c,"class")&&(d=d+" "+c["class"],delete c["class"]),b.isObjectEmpty(c)||b.mergeObject(e,c));return{nodeName:"button",className:d,childNodes:[{nodeName:"span",childNodes:[{nodeName:"span",text:a}]}],attr:e}},backToLogin:{nodeName:"div",className:g.formOptions,childNodes:[{nodeName:"span",className:g.formOption_backToLogin,text:"Back to Login"}]},logoutTab:[{nodeName:"span",className:g.windowLogout,text:"LOGOUT"},{nodeName:"span",className:g.windowUserName}],
buildModal:function(a,b){b=[{nodeName:"a",className:g.logo,attr:{href:r.paths.website},text:"Pinup"},{nodeName:"h2",text:a}].concat(b);return{nodeName:"div",className:g.modalMsg,childNodes:b}},simpleAdd:function(a,b){return{nodeName:a,text:b}}};z={formTagCreate:h.buildForm("PIN_newTagForm",h.logoutTab.concat([h.buildHeader("ADD NEW TAG"),h.buildFormInput("hidden","strWebReferer"),h.buildFormInput("hidden","strImageURL"),h.buildFormInput("hidden","nPosX"),h.buildFormInput("hidden","nPosY"),h.buildFormLabel("Tag name",
h.buildFormInput("text","strTagName")),h.buildFormLabel("Keywords",h.buildFormInput("text","strKeywords")),h.buildFormLabel("Destination url",h.buildFormInput("text","strWebLink"))]),"SAVE & PUBLISH TAG"),formRegister:h.buildForm("PIN_registerForm",[h.buildHeader("ACCOUNT REGISTRATION"),h.buildFormLabel("Full Name",h.buildFormInput("text","strFullName")),h.buildFormLabel("E-mail",h.buildFormInput("text","strUsername")),h.buildFormLabel("Password",h.buildFormInput("password","strPassword")),h.buildFormLabel("Confirm Pass",
h.buildFormInput("password","strConfirmPass")),h.buildHeader("SITE REGISTRATION"),h.simpleAdd("p","For Pinup to work securely, it requires users to link their website to their account. Please provide us with some basic information about your website."),h.buildFormLabel("Website Name",h.buildFormInput("text","strWebName")),h.buildFormLabel("Website Domain",h.buildFormInput("text","strWebURL")),h.backToLogin],"REGISTER"),formLogin:h.buildForm("PIN_loginForm",[h.buildHeader("ACCOUNT LOGIN"),h.buildFormLabel("E-mail",
h.buildFormInput("text","strUsername")),h.buildFormLabel("Password",h.buildFormInput("password","strPassword")),{nodeName:"div",className:g.formOptions,childNodes:[{nodeName:"span",className:g.formOption_forgotPass,text:"Forgot your password?"},{nodeName:"span",className:g.formOption_register,text:"Sign Up"}]}],"LOGIN"),formForgot:h.buildForm("PIN_formForgot",[h.buildHeader("FORGOT PASSWORD"),h.buildFormLabel("E-mail",h.buildFormInput("text","strUsername")),h.backToLogin],"RETRIEVE PASSWORD"),formSettings:h.buildForm("PIN_formSettings",
h.logoutTab.concat([h.buildHeader("UPDATE SETTINGS"),h.simpleAdd("p","This form allows administrators to change how Pinup interacts with images. This form is not accessible to the public."),h.buildButton("REPOSITION TAGS",function(){var a={};a["class"]=g.formBtnLeft;a.name="btnRepositionTags";return a}),h.buildButton("REMOVE TAGS",function(){var a={};a["class"]=g.formBtnLeft;a.name="btnRemoveTags";return a}),h.buildButton("OPEN IMAGES IN LIGHTBOX",function(){var a={};a["class"]=g.formBtnLeft;a.name=
"btnOpenLightbox";return a})])),msgTagDeleted:h.buildModal("This tag has been deleted.",[h.simpleAdd("p","Note: because you are either the owner of the image, or the tags creator, you are able to delete it whereas the public would only be able to report.")]),msgForgot:h.buildModal("You have requested a new password.",[h.simpleAdd("p","A new password has been generated and sent to your email address. We recommend that you change it asap!")]),msgRegistered:h.buildModal("Registration was successful.",
[h.simpleAdd("p","You have just created your account! Easy right? However there is one last step: your email needs to be authenticated. Please check your inbox for a confirmation email. If you do not receive an email within the hour, please contact our support team.")]),msgNoPermission:h.buildModal("You do not have sufficient permission.",[h.simpleAdd("p","The owner of this website has requested your account not be able to add or request tags. Please contact the site owner for more information.")]),
msgImageDisabled:h.buildModal("This image has been disabled.",[h.simpleAdd("p","The Pinup interface will no longer show on this image. If you wish the enable the interface, you can do so in the settings window.")]),msgImageEnabled:h.buildModal("This image has been enabled.",[h.simpleAdd("p","The Pinup interface will now show on this image. If you wish the disabled the interface, you can do so in the settings window.")]),msgFirstTag:h.buildModal("This appears to be your first tag!",[h.simpleAdd("p",
"Luckily for you, we have made it as easy as possible. Here are some simple instructions to get you started."),{nodeName:"ol",childNodes:[{nodeName:"li",text:"Click on the image where you would like the tag to appear."},{nodeName:"li",text:"A popup form will obtain some information relevant to the tag."},{nodeName:"li",text:"Click save and you're off to the races."}]},h.buildButton("GREAT, LET'S GET STARTED")]),confirmPrompt:{nodeName:"div",className:g.prompt,childNodes:[h.buildHeader("PLEASE CONFIRM"),
{nodeName:"p",className:g.promptMessage},h.buildButton("YES I DO",{"class":g.promptAccept}),h.buildButton("NO THANKS",{"class":g.promptDeny})]}};ha.prototype={init:function(){var a=this,c=b.domAppend("div",a.scope.privateElements.imgOverlay,{"class":g.guiLeftHolder}),d=b.domAppend("div",a.scope.privateElements.imgOverlay,{"class":g.guiRightHolder}),e=b.domAppend("span",d,{"class":g.guiTopR+" "+g.btnCancel});a.offsetLeft=b.getWidth(c)-Math.abs(b.getStyle(c,"left"));a.offsetRight=10;b.disableSelection(e);
b.addEvent(e,k.mouseover,function(){j.animations?b.animate(d,"right",0,j.navAniSpeed):b.setStyle(d,"right",0)});b.addEvent(e,k.mouseout,function(){j.animations?b.animate(d,"right",-a.offsetRight,j.navAniSpeed):b.setStyle(d,"right",-a.offsetRight)});a.scope.privateElements.guiLeftHolder=c;a.scope.privateElements.guiRightHolder=d;a.scope.privateElements.btnCancel=e},ownerInit:function(){var a=this,c=b.domAppend("span",a.scope.privateElements.imgOverlay,{"class":g.btnSettings});b.setAlpha(c,0.3);b.addEvent(c,
k.mouseover,function(){j.animations?b.fadeTo(c,1,j.navAniSpeed):b.setAlpha(c,1)});b.addEvent(c,k.mouseout,function(){j.animations?b.fadeTo(c,0.3,j.navAniSpeed):b.setAlpha(c,0.3)});b.click(c,function(){f.promptSettings(a.scope.image)});a.scope.privateElements.btnSettings=c},check:function(){this.allowPrivateInterfaces=this.hasOwnerPrivileges();this.hasUi||this.build()},build:function(){var a=this;b.loopArray(a.leftNavItems,function(c){if(!c.isPrivate||a.allowPrivateInterfaces){var d=b.domAppend("span",
a.scope.privateElements.guiLeftHolder,{"class":g.guiBotL+" "+c.className},c.label);b.disableSelection(d);f.setFluidWidth(d);b.addEvent(d,k.mouseover,function(){var c=b.attribute(this,"fluidwidth")-a.offsetLeft+5;j.animations?b.animate(this,"left",c,j.navAniSpeed):b.setStyle(this,"left",c)});b.addEvent(d,k.mouseout,function(){j.animations?b.animate(this,"left",0,j.navAniSpeed):b.setStyle(this,"left",0)});b.click(d,function(){c.event(a,d)})}});a.allowPrivateInterfaces&&a.ownerInit();a.hasUi=!0},destroy:function(){var a=
b.getElementsByClassName(g.guiBotL,this.scope.privateElements.guiLeftHolder);0<a.length&&b.loopArray(a,function(a){b.removeElement(a)});this.scope.privateElements.btnSettings&&b.removeElement(this.scope.privateElements.btnSettings);this.hasUi=!1},enableCancelMode:function(a,c){var d=this,e=d.scope.privateElements.guiRightHolder,g=d.scope.privateElements.btnCancel,F=function(){d.disableCancelMode(c)};b.click(g,F);f.newKeyListener(27,d.scope.pinUID,F);b.textContent(g,a);b.show(e);j.animations&&b.animate(e,
"right",-d.offsetRight,j.navAniSpeed)},disableCancelMode:function(a){var c=this.scope.privateElements.guiRightHolder,d=this.scope.privateElements.btnCancel,e;b.removeEvent(d,k.click);f.removeKeyListener(27,this.scope.pinUID);j.animations?(e=f.deactivateEvents(d,[k.mouseover,k.mouseout]),b.animate(c,"right",-b.getWidth(c),j.navAniSpeed,function(){f.activateEvents(d,e);b.hide(c);b.removeChildren(d)})):(b.hide(c),b.removeChildren(d));a&&a.call()},drawTooltip:function(a,c){var d,e=c.cornerRadius,g=c.pointerWidth,
F=c.pointerHeight,E=c.canvasPadding,j=c.halfPixel;d=c.width;var h=c.height,q=c.width-2*E-2*j,k=c.height-2*E-2*j,l,n=c.orientation,m,r=n===p.tooltipOrientations.bottom?F:0,t=n===p.tooltipOrientations.right?g:0,s=F/2,v=g/2,u=F/2,C=g/2,y=!0,w=!0,x=!0,A=!0;if(n===p.tooltipOrientations.top||n===p.tooltipOrientations.bottom)m=q/2,h+=F,c.offsetLeft<d/2?(m=c.offsetLeft-E,c.offsetLeft-E-e<g/2&&(C=0,y=n===p.tooltipOrientations.bottom?!1:!0,x=n===p.tooltipOrientations.top?!1:!0)):c.offsetRight<d/2&&(m=d-c.offsetRight-
E,c.offsetRight-E-e<g/2&&(v=0,w=n===p.tooltipOrientations.bottom?!1:!0,A=n===p.tooltipOrientations.top?!1:!0));else if(n===p.tooltipOrientations.left||n===p.tooltipOrientations.right)m=k/2,d+=g;0>=e&&(A=x=w=y=!1);a.width=d;a.height=h;b.setWidth(a,d);b.setHeight(a,h);d=f.getCanvasContext(a,"2d");d.translate(E+t+j,E+r+j);d.beginPath();y?(d.moveTo(0,e),d.arc(e,e,e,180*(Math.PI/180),270*(Math.PI/180),!1)):d.moveTo(0,0);n===p.tooltipOrientations.bottom&&(d.lineTo(m-C,0),d.lineTo(m,-F),d.lineTo(m+v,0));
w?(d.lineTo(q-e,0),d.arc(q-e,e,e,270*(Math.PI/180),0*(Math.PI/180),!1)):d.lineTo(q,0);n===p.tooltipOrientations.left&&(d.lineTo(q,m-s),d.lineTo(q+g,m),d.lineTo(q,m+u));A?(d.lineTo(q,k-e),d.arc(q-e,k-e,e,0*(Math.PI/180),90*(Math.PI/180),!1)):d.lineTo(q,k);n===p.tooltipOrientations.top&&(d.lineTo(m+v,k),d.lineTo(m,k+F),d.lineTo(m-C,k));x?d.arc(e,k-e,e,90*(Math.PI/180),180*(Math.PI/180),!1):d.lineTo(0,k);n===p.tooltipOrientations.right&&(d.lineTo(0,m+u),d.lineTo(-g,m),d.lineTo(0,m-s));d.closePath();
c.allowShadow&&(d.shadowColor=c.theme.shadowColor,d.shadowOffsetX=c.theme.shadowOffsetX,d.shadowOffsetY=c.theme.shadowOffsetY,d.shadowBlur=c.theme.shadowBlur);c.theme.backgroundStyle===p.canvasDrawStyles.radial?(l=d.createRadialGradient(q/2,k/2,0,q/2,k/2,q>k?q:k),b.loopArray(c.theme.backgroundColor.split(" "),function(a){a=a.split("-");l.addColorStop(a[0],a[1])})):c.theme.backgroundStyle===p.canvasDrawStyles.linear?(l=d.createLinearGradient(q/2,0,q/2,k),b.loopArray(c.theme.backgroundColor.split(" "),
function(a){a=a.split("-");l.addColorStop(a[0],a[1])})):c.theme.backgroundStyle===p.canvasDrawStyles.solid&&(l=c.theme.backgroundColor);d.fillStyle=l;d.fill();c.allowStroke&&(c.allowShadow&&(d.shadowColor=null,d.shadowOffsetX=null,d.shadowOffsetY=null,d.shadowBlur=null),d.strokeStyle=c.theme.strokeColor,d.lineWidth=c.theme.strokeWidth,d.stroke())},hasOwnerPrivileges:function(){return!!w[t.user.isOwner]},show:function(a){var c=this.scope.privateElements.guiLeftHolder,d=this.scope.privateElements.btnSettings,
e=this.offsetLeft-b.getWidth(c);this.isHidden=!1;j.animations?(b.show(c),b.animate(c,"left",e,j.navAniSpeed),d&&(b.show(d),b.fadeTo(d,0.3,j.navAniSpeed))):(b.setStyle(c,"left",e),d&&b.show(d))},hide:function(a){var c=this.scope.privateElements.guiLeftHolder,d=this.scope.privateElements.btnSettings,e=-b.getWidth(c),g=[];this.isHidden=!0;j.animations?(d&&(g[0]=f.deactivateEvents(d,[k.mouseover,k.mouseout]),b.fadeOut(d,j.navAniSpeed,function(){f.activateEvents(d,g[0]);b.hide(d)})),g[1]=f.deactivateEvents(c,
[k.mouseover,k.mouseout]),b.animate(c,"left",e,j.navAniSpeed,function(){f.activateEvents(c,g[1]);b.hide(c)}),b.loopArray(c.children,function(a){var c=g.length++;g[c]=f.deactivateEvents(a,[k.mouseover,k.mouseout]);b.animate(a,"left",0,j.navAniSpeed,function(){f.activateEvents(a,g[c])})})):(b.setStyle(c,"left",e),d&&b.hide(d))},toggle:function(a){this.isHidden?this.show(a):this.hide(a)}};ia.prototype={destroy:function(a){a?b.removeElement(this.privateElements.imgNode):b.replaceElement(this.privateElements.imgNode,
this.imageClone);delete H[this.uid];delete D[this.uid];delete I[this.uid]},init:function(){var a=this,c=b.getComputedStyles(a.image),d=s.checkImage+a.imageCloneSrc;b.attribute(a.image,"loaded",pa[1]);b.addClass(a.image,g.image);a.privateElements.imgNode=b.domWrap("div",a.image,{"class":g.node});"inline"===c.display&&b.addClass(a.privateElements.imgNode,g.inlineNode);H[a.uid]={instance:a,imgGUID:b.getGUID(a.image)};b.click(a.privateElements.imgNode);a.settings.cssHelper&&a.styleHelper(c);b.setWidth(a.image,
a.dimensions.width);b.setHeight(a.image,a.dimensions.height);b.setStyle(a.image,"maxWidth",a.dimensions.width);b.setStyle(a.image,"maxHeight",a.dimensions.height);b.attribute(a.image,"width",null);b.attribute(a.image,"height",null);b.setWidth(a.privateElements.imgNode,a.dimensions.width);b.setHeight(a.privateElements.imgNode,a.dimensions.height);a.settings.posHelper&&a.positionHelper();a.privateElements.sectionBody=b.domWrap("div",a.image,{"class":g.sectionBody});b.setWidth(a.privateElements.sectionBody,
a.dimensions.width);b.setHeight(a.privateElements.sectionBody,a.dimensions.height);a.privateElements.imgOverlay=b.domAppend("div",a.privateElements.sectionBody,{"class":g.overlay});b.setWidth(a.privateElements.imgOverlay,a.dimensions.width);b.setHeight(a.privateElements.imgOverlay,a.dimensions.height);a.privateElements.imgTagHolder=b.domAppend("div",a.privateElements.imgOverlay,{"class":g.tagHolder});a.preRun();(c=f.getLocalStorage(d))?(a.imageSrc=c,a.postRun()):b.loadJSONP(r.names.checkImage,{strImageURL:a.imageSrc},
function(b){b&&(a.imageSrc=b);f.setLocalStorage(d,a.imageSrc);a.postRun()})},positionHelper:function(){var a=b.getCumulativeOffset(this.image),c="absolute"===b.getStyle(this.privateElements.imgNode,"position")?{top:"top",left:"left"}:{top:"marginTop",left:"marginLeft"},d=b.getStyle(this.privateElements.imgNode,c.left)||0,e=b.getStyle(this.privateElements.imgNode,c.top)||0,d=this.dimensions.offsetLeft-a.x+d,a=this.dimensions.offsetTop-a.y+e;0<d&&(b.setStyle(this.privateElements.imgNode,c.left,d),this.dimensions.offsetLeft=
d);0<a&&(b.setStyle(this.privateElements.imgNode,c.top,a),this.dimensions.offsetTop=a)},styleHelper:function(a){var c=this,d,e;delete a.display;"static"===a.position&&delete a.position;b.attribute(c.image,"style",null);b.attribute(c.image,"align",null);b.attribute(c.image,"hspace",null);b.attribute(c.image,"vspace",null);d=b.getComputedStyles(c.privateElements.imgNode);e=b.getComputedStyles(c.image);b.loopObject(a,function(a,f){if(!b.inArray(["width","height","color"],a)){var g=d[a],k=e[a];f!==g&&
b.setStyle(c.privateElements.imgNode,a,f);k!==g&&b.setStyle(c.image,a,g)}})},preRun:function(){var a=this;!0===a.settings.allowBottomLinks&&(a.privateElements.sectionFooter=b.domAppend("div",a.privateElements.imgNode,{"class":g.sectionFooter}),a.privateElements.linkHolder=b.domAppend("div",a.privateElements.sectionFooter,{"class":g.linkHolder}),b.domAppend("div",a.privateElements.sectionFooter,{"class":g.linkHolderBackground}),b.hide(a.privateElements.sectionFooter));a.ui=new ha(a);a.ui.init();b.addEvent(a.privateElements.imgNode,
k.mouseover,function(b){(new f.MouseBoundaryCrossing(b,this)).enteredLandmark&&a.enableImgNode()});b.addEvent(a.privateElements.imgNode,k.mouseout,function(b){(new f.MouseBoundaryCrossing(b,this)).leftLandmark&&a.disableImgNode()});a.settings.alwaysShowTags&&b.addClass(a.privateElements.imgNode,g.actionOn)},postRun:function(){var a=this;a.settings.alwaysShowTags&&f.checkLogin(null,null,function(){f.methodSessionChange(a)})},methodAddNewTag:function(a){var b=this;f.openPrivateWindow(z.formTagCreate,
function(){var d=l.forms.PIN_newTagForm;d.elements.strWebReferer.value=ma;d.elements.strImageURL.value=b.imageSrc;d.elements.nPosX.value=a.x;d.elements.nPosY.value=a.y;f.manageTagSuggestionList(d);f.manageKeywords(d.elements.strKeywords);f.validWebUrl(d.elements.strWebLink);f.manageFormSubmit(d,r.names.tagCreate,["*"],function(a){a?f.displayFormError(this,a):(f.closeWindow(),b.updateNode(!0,!0),w[t.user.tagTotal]+=1)})})},updateNode:function(a,c){var d=this,e=function(){var a=G[this.imageSrc][1];
this.tagsVersion=G[this.imageSrc][0];a&&!b.isObjectEmpty(a)&&(this.drawTagData(a),this.settings.allowBottomLinks&&this.drawLinkData(a))};a|=0;!0!==d.updateInProgress&&(d.updateInProgress=!0,c|0&&delete G[d.imageSrc],b.hasProperty(G,d.imageSrc)?((a||d.tagsVersion!==G[d.imageSrc][0])&&e.call(d),d.updateInProgress=!1):(b.hasProperty(K,d.uid)||(K[d.uid]=[]),b.inArray(K[d.uid],d)||K[d.uid].push(d),1<K[d.uid].length||b.loadJSONP(r.names.getTags,{strImageURL:d.imageSrc},function(a){null!==a&&(G[d.imageSrc]=
[(new Date).getTime(),a],b.loopArray(K[d.uid],function(a){e.call(a)}),delete K[d.uid]);d.updateInProgress=!1})))},tagMouseoverEvent:function(a){var c=b.getElementsByClassName(g.tagDot,a)[0],d=b.getElementsByClassName(g.tagOutline,a)[0],e=b.getElementsByClassName(g.tagBubble,a)[0],B={};b.setStyle(a,"zIndex",999);b.setStyle(this.privateElements.imgTagHolder,"zIndex",999);c&&d&&(b.show(d),c=2*this.settings.dotOutlineSize+b.getWidth(c),B.width=c,B.height=c,B.marginTop=-Math.floor(c/2),B.marginLeft=-Math.floor(c/
2),j.animations?b.animate(d,B,200):b.setStyles(d,B));e&&this.allowTagBubble&&b.show(e);(a=f.getTagGuidObject(a))&&b.loadJSONP(r.names.logTagHover,a)},tagMouseoutEvent:function(a){var c=b.getElementsByClassName(g.tagOutline,a)[0],d=b.getElementsByClassName(g.tagBubble,a)[0],e={};b.setStyle(a,"zIndex",1);b.setStyle(this.privateElements.imgTagHolder,"zIndex",1);c&&(e.width=0,e.height=0,e.marginTop=0,e.marginLeft=0,j.animations?b.animate(c,e,600,function(){b.hide(this)}):(b.setStyles(c,e),b.hide(c)));
d&&b.hide(d)},clearTagData:function(){b.loopObjectKeys(G,function(a){delete G[a]})},drawTagData:function(a){var c=this,d=b.isElementEmpty(c.privateElements.imgTagHolder);b.removeChildren(c.privateElements.imgTagHolder);b.setAlpha(c.privateElements.imgTagHolder,0);b.loopObject(a,function(a){var d=a[0],F=b.randomID(12),h,m,n,q,s=[];q={};q.id="tagId_"+c.uid+"-"+F;q["class"]=g.tag+" "+p.availableDotSizes[j.dotSize];q.posx=d[t.tags.posX];q.posy=d[t.tags.posY];1<a.length?(b.loopObject(a,function(a){s.push(a[t.tags.guid])}),
q.taguids=s.join("_")):q.taguid=d[t.tags.guid];h=b.domAppend("div",c.privateElements.imgTagHolder,q);b.setStyle(h,"left",String(100*d[t.tags.posX])+"%");b.setStyle(h,"top",String(100*d[t.tags.posY])+"%");q={};q["class"]=g.tagDot;m=b.domAppend("a",h,q);f.setWindowLink(m,r.paths.webloc+d[t.tags.guid]);0<c.settings.dotOutlineSize&&(q={},q["class"]=g.tagOutline,d=b.domAppend("span",h,q),m={width:0,height:0,marginTop:0,marginLeft:0},b.setStyles(d,m));c.settings.tooltip&&(n=l.createDocumentFragment(),b.hasProperty(I,
c.uid)||(I[c.uid]={}),b.loopArray(a,function(d,B){var h=B[t.tags.name],k=B[t.tags.keywords].join(),j=B[t.tags.webLink],l=B[t.tags.guid],m=B[t.tags.ownerGuid];I[c.uid][l]=F;q={};q.id="tagId_"+F+"-"+l;q["class"]=g.tagLink;q.taguid=l;q.tagname=h;q.keywords=k;q.weblink=j;q.ownerid=m;k=b.domAppend("span",n,q);h=25<h.length?h.substr(0,25)+"...":h;q={};q["class"]=g.tagLinkText;h=b.domAppend("a",k,q,h);f.setWindowLink(h,r.paths.webloc+l);c.settings.tooltipURL&&(b.loopArray(oa,function(a){j=j.replace(a,"")}),
j=j.replace(ea,""),25<j.length&&(j=j.substr(0,25)+"..."),q={},q["class"]=g.tagLinkURL,b.domAppend("span",k,q,j));c.settings.allowShare&&(q={},q["class"]=g.tagLinkLike,b.click(b.domAppend("span",k,q,"like"),function(){c.manageTagLike(this)}),b.setStyle(k,"paddingRight",18));d+1===a.length&&b.addClass(k,g.lastItem)}),d=c.drawTagBubble(h,n),b.hide(d));b.addEvent(h,k.mouseover,function(a){var d=b.getParentByClassName(this,g.tag);(new f.MouseBoundaryCrossing(a,this)).enteredLandmark&&c.tagMouseoverEvent(d)});
b.addEvent(h,k.mouseout,function(a){var d=b.getParentByClassName(this,g.tag);(new f.MouseBoundaryCrossing(a,this)).leftLandmark&&c.tagMouseoutEvent(d)})});d?b.fadeIn(c.privateElements.imgTagHolder,800):b.setAlpha(c.privateElements.imgTagHolder,1)},drawTagBubble:function(a,c){var d=this,e=b.getElementsByClassName(g.tagDot,a)[0],f,h,k,j,l,q,m,n,r,t,s,u,w,x,A,C={},y=d.settings.tooltipOrientation,z,D;z={};z["class"]=g.tagBubble;f=b.domAppend("span",a,z);z={};z["class"]=g.tagBubbleContent;h=b.domAppend("span",
f,z);b.domAppend(c,h);k=b.getCumulativeOffset(a);j=b.getCumulativeOffset(d.privateElements.imgTagHolder);l=d.settings.canvas.stroke&&0!==d.settings.canvas.theme.strokeWidth%2?0.5:0;e=b.getWidth(e)/2;q=b.getWidth(f)+2*l;m=b.getHeight(f)+2*l;n=b.getWidth(d.privateElements.imgTagHolder);r=b.getHeight(d.privateElements.imgTagHolder);t=b.getHeight(h);s=k.y-j.y;r-=s;u=k.x-j.x;w=n-u;x=d.settings.canvas.tailWidth;A=d.settings.canvas.tailHeight;k=q;j=m;C.top="auto";C.right="auto";C.bottom="auto";C.left="auto";
if(y===p.tooltipOrientations.top||y===p.tooltipOrientations.bottom)C.left=-(q/2),j+=A;else if(y===p.tooltipOrientations.left||y===p.tooltipOrientations.right)x=d.settings.canvas.tailHeight,A=d.settings.canvas.tailWidth,C.top=-(m/2),k+=x;y===p.tooltipOrientations.top?j+e>s&&(y=p.tooltipOrientations.bottom):y===p.tooltipOrientations.right?k+e>w&&(y=p.tooltipOrientations.left):y===p.tooltipOrientations.bottom?j+e>r&&(y=p.tooltipOrientations.top):y===p.tooltipOrientations.left&&k+e>u&&(y=p.tooltipOrientations.right);
y===p.tooltipOrientations.top?C.bottom=e:y===p.tooltipOrientations.right?(C.left=e+1,b.setStyle(h,"paddingLeft",10+x)):y===p.tooltipOrientations.bottom?(C.top=e+1,b.setStyle(h,"top",j-t)):y===p.tooltipOrientations.left&&(C.right=e,b.setStyle(h,"paddingRight",10+x));if(y===p.tooltipOrientations.top||y===p.tooltipOrientations.bottom)u<q/2?C.left=-u:w<q/2&&(C.left=-(q-w));b.setStyles(f,C);b.setWidth(f,k);b.setHeight(f,j);b.runInterval(30,30,function(){return v.canvas},function(){z={};z["class"]=g.tagBubbleCanvas;
D=b.domAppend("canvas",f,z);D.pinupCanvasProperties={theme:d.settings.canvas.theme,allowStroke:d.settings.canvas.stroke,allowShadow:d.settings.canvas.shadow,cornerRadius:d.settings.canvas.cornerRadius,canvasPadding:3,halfPixel:l,width:q,height:m,offsetLeft:u,offsetRight:w,pointerWidth:x,pointerHeight:A,orientation:y};d.ui.drawTooltip(D,D.pinupCanvasProperties)},function(){});return f},drawLinkData:function(a){var c=this,d=c.privateElements.linkHolder,e=function(){var a=b.attribute(this,"taguid");
b.hasProperty(I,c.uid)&&b.hasProperty(I[c.uid],a)&&c.tagMouseoverEvent(l.getElementById("tagId_"+c.uid+"-"+I[c.uid][a]))},h=function(){b.loopArray(b.getElementsByClassName(g.tag,c.privateElements.imgTagHolder),function(a){c.tagMouseoutEvent(a)})};b.removeChildren(d);b.loopObject(a,function(a){b.loopArray(a,function(a){var j,l;l={};l["class"]=g.link;l.taguid=a[t.tags.guid];j=b.domAppend("a",d,l);f.setWindowLink(j,r.paths.webloc+a[t.tags.guid]);l={};l["class"]=g.iconLabel;b.domAppend("span",j,l);b.appendText(j,
a[t.tags.name]);c.settings.tooltip&&(b.addEvent(j,k.mouseover,e),b.addEvent(j,k.mouseout,h))})});b.isElementEmpty(d)?(b.hide(c.privateElements.sectionFooter),b.hide(d),b.setHeight(c.privateElements.imgNode,c.dimensions.height)):(b.show(c.privateElements.sectionFooter),b.show(d),b.setHeight(c.privateElements.imgNode,b.getHeight(d)+c.dimensions.height))},enableImgNode:function(){var a=this;a.disallowNodeUpdate||(a.settings.alwaysShowTags||b.addClass(a.privateElements.imgNode,g.actionOn),f.checkLogin(null,
null,function(){f.methodSessionChange(a)}),f.newKeyListener(113,a.uid,function(){a.ui.toggle()}))},disableImgNode:function(){this.disallowNodeUpdate||(this.settings.alwaysShowTags||b.removeClass(this.privateElements.imgNode,g.actionOn),f.removeKeyListener(113,this.uid))},resetTagDotBehavior:function(){b.loopArray(b.getElementsByClassName(g.tagDot,this.privateElements.imgTagHolder),function(a){var c=f.getTagGuidObject(a.parentNode),c=c?b.hasProperty(c,"tagGUID")?c.tagGUID:b.hasProperty(c,"tagMultiGUID")?
c.tagMultiGUID.split("_")[0]:void 0:void 0;b.removeAllEvents(a);c&&f.setWindowLink(a,r.paths.webloc+c)})},stopTaggingMode:function(){this.disallowNodeUpdate=!1;this.allowTagBubble=!0;b.removeEvent(this.privateElements.imgTagHolder,k.click);b.removeClass(this.privateElements.imgTagHolder,g.button);this.resetTagDotBehavior();this.ui.show();this.ui.disableCancelMode();b.removeClass(this.privateElements.imgNode,g.taggingMode);b.hasClass(m.pInstWrapper,g.actionShowWin)||b.addClass(this.privateElements.imgNode,
g.actionOn)},startTaggingMode:function(a){var c=this;f.checkPermission(function(){c.disallowNodeUpdate=!0;c.allowTagBubble=!1;b.removeClass(c.privateElements.imgNode,g.actionOn);b.addClass(c.privateElements.imgNode,g.taggingMode);b.click(c.privateElements.imgTagHolder,function(b){c.stopTaggingMode();a&&a.call(c,f.getPosPercentage(b))},!0);b.loopArray(b.getElementsByClassName(g.tagDot,c.privateElements.imgTagHolder),function(d){b.removeAllEvents(d);b.click(d,function(){c.stopTaggingMode();a&&a.call(c,
{x:b.attribute(this.parentNode,"posx"),y:b.attribute(this.parentNode,"posy")})},!0)});c.ui.hide();c.ui.enableCancelMode("CANCEL",function(){c.stopTaggingMode()})})},stopTagRepositionMode:function(){this.disallowNodeUpdate=!1;this.allowTagBubble=!0;b.hasEvent(l,k.mouseup)&&(b.fireEvent(l,k.mouseup),b.removeEvent(l,k.mouseup),b.removeClass(this.privateElements.imgNode,g.handOver));this.resetTagDotBehavior();this.ui.show();this.ui.disableCancelMode();b.removeClass(this.privateElements.imgNode,g.repositionMode);
b.addClass(this.privateElements.imgNode,g.actionOn)},startTagRepositionMode:function(){var a=this;f.checkPermission(function(){a.disallowNodeUpdate=!0;a.allowTagBubble=!1;b.removeClass(a.privateElements.imgNode,g.actionOn);b.addClass(a.privateElements.imgNode,g.repositionMode);b.loopArray(b.getElementsByClassName(g.tag,a.privateElements.imgTagHolder),function(c){var d=b.getElementsByClassName(g.tagDot,c)[0];b.removeAllEvents(d);b.addEvent(d,k.mouseover,function(){b.addClass(a.privateElements.imgNode,
g.handOver)});b.addEvent(d,k.mouseout,function(){b.removeClass(a.privateElements.imgNode,g.handOver)});b.addEvent(d,k.mousedown,function(e){b.stopBubble(e);b.addClass(a.privateElements.imgNode,g.handDrag);f.startDragging(c);b.addEvent(l,k.mouseup,function(){var e=f.getTagGuidObject(d.parentNode);e&&(b.removeClass(a.privateElements.imgNode,g.handDrag),f.stopDragging(c),b.removeEvent(l,k.mouseup),e[t.tags.imagePath]=a.imageSrc,e[t.tags.posX]=b.attribute(c,"posx"),e[t.tags.posY]=b.attribute(c,"posy"),
b.loadJSONP(r.names.tagPosition,e,a.clearTagData))})})});a.ui.hide();a.ui.enableCancelMode("DONE",function(){a.stopTagRepositionMode()})})},stopTagRemovalMode:function(){this.disallowNodeUpdate=!1;this.allowTagBubble=!0;this.resetTagDotBehavior();this.ui.show();this.ui.disableCancelMode();b.removeClass(this.privateElements.imgNode,g.removalMode);b.addClass(this.privateElements.imgNode,g.actionOn)},startTagRemovalMode:function(){var a=this;f.checkPermission(function(){a.disallowNodeUpdate=!0;a.allowTagBubble=
!1;b.removeClass(a.privateElements.imgNode,g.actionOn);b.addClass(a.privateElements.imgNode,g.removalMode);b.loopArray(b.getElementsByClassName(g.tag,a.privateElements.imgTagHolder),function(c){var d=b.getElementsByClassName(g.tagDot,c)[0];b.removeAllEvents(d);b.click(d,function(){var c=1<b.getElementsByClassName(g.tagBubbleContent,d.parentNode)[0].children.length?x.removeMultiTags:x.removeTag;f.promptConfirm(c,function(){var c=f.getTagGuidObject(d.parentNode);c&&b.loadJSONP(r.names.tagRemove,c,function(e){b.isUndefined(e)&&
(f.closeWindow(),b.removeElement(d.parentNode),j.allowBottomLinks&&(b.hasProperty(c,"tagGUID")?b.loopArray(a.privateElements.linkHolder.children,function(a){if(b.attribute(a,"taguid")===c.tagGUID)return b.removeElement(a),null}):b.hasProperty(c,"tagMultiGUID")&&b.loopArray(c.tagMultiGUID.split("_"),function(c){b.loopArray(a.privateElements.linkHolder.children,function(a){if(b.attribute(a,"taguid")===c)return b.removeElement(a),null})})),a.clearTagData())})})})});a.ui.hide();a.ui.enableCancelMode("DONE",
function(){a.stopTagRemovalMode()})})},manageTagLike:function(a){var c=this,d=b.getParentByClassName(a,g.tag),e=b.getParentByClassName(a,g.tagLink);a=b.getElementsByClassName(g.tagBubble,d)[0];var j,h=b.attribute(e,"tagname"),l=b.attribute(e,"weblink"),m;m={};m["class"]=g.shareHolder;e=b.newElement("div",m);m={};m["class"]=g.shareHeader;b.domAppend("span",e,m,"SHARE THIS ON");m={};m["class"]=g.shareButtons;j=b.domAppend("div",e,m);m={};m["class"]=g.shareButton+" st_twitter_large";m.href=r.paths.twitter+
b.getParamsFromObject({text:h+" found at ",url:encodeURI(l)});b.click(b.domAppend("a",j,m),function(){f.openPopupWindow(b.attribute(this,"href"),480,400)});m={};m["class"]=g.shareButton+" st_facebook_large";m.href=r.paths.facebook+b.getParamsFromObject({u:encodeURI(l),t:encodeURIComponent(h)});b.click(b.domAppend("a",j,m),function(){f.openPopupWindow(b.attribute(this,"href"),1E3,640)});c.updateInProgress=!0;b.removeElement(a);a=c.drawTagBubble(d,e);b.removeEvent(d,k.mouseout);b.addEvent(d,k.mouseout,
function(a){(new f.MouseBoundaryCrossing(a,this)).leftLandmark&&(c.updateInProgress=!1,c.updateNode(!0))})}};f={systemStart:function(){var a=l.getElementById("PinupSEO"),c=function(){clearTimeout(qa);qa=setTimeout(function(){b.isObjectEmpty(J)?j.forceListen||(b.removeEvent(l,v.propertychange),b.removeEvent(l,k.scroll)):b.loopObject(J,function(a){f.loadImage(a.image)});j.forceListen&&f.checkForImages()},j.scrollDelay)};if(!L){L=!0;W=V=U=0;j.custom&&(!b.isObjectEmpty(j.custom)&&b.hasProperty(j.custom,
l.body.id))&&f.updateSettings(j.custom[l.body.id]);f.initKeyListener();f.checkSupport();b.isElement(a)&&(m.pseudoSEO=a);for(m.pInstActive=b.newElement("div",{id:g.docBody,"class":g.docBody});l.body.firstChild;)m.pInstActive.appendChild(l.body.firstChild);l.body.appendChild(m.pInstActive);j.animations||b.addClass(m.pInstActive,g.noAnimation);v.rgba||b.addClass(m.pInstActive,g.noRgbaSupport);v.boxShadow||b.addClass(m.pInstActive,g.noBoxShadowSupport);v.borderRadius||b.addClass(m.pInstActive,g.noBorderRadiusSupport);
v.canvas||b.isUndefined(n[s.vmlCanvas])&&b.loadScript(r.paths.excanvas,function(){n[s.vmlCanvas].init_(l);v.canvas=f.getCanvasContext(l.createElement("canvas"))});m.pInstWrapper=b.domAppend("div",m.pInstActive,{"class":g.wrapper});j.allowThemeManager&&f.manageTheme(j.themeFile);m.pInstWindow=b.domAppend("div",m.pInstWrapper,{"class":g.window});m.pInstWindowOverlay=b.domAppend("div",m.pInstWrapper,{"class":g.windowOverlay});m.pInstWindowClose=b.domAppend("span",m.pInstWindow,{"class":g.windowClose},
"close");m.pInstWindowBody=b.domAppend("div",m.pInstWindow,{"class":g.windowBody});m.pInstWindowBackground=b.domAppend("div",m.pInstWindow,{"class":g.windowBackground});b.click(m.pInstWindowOverlay,f.closeWindow);b.click(m.pInstWindowClose,f.closeWindow);f.checkLogin(null,null,function(){f.checkForImages();if(j.smartLoad&&!b.isObjectEmpty(J)||j.forceListen)b.addEvent(l,v.propertychange,c),b.addEvent(l,k.scroll,c);j.onReady&&j.onReady.call(n[s.root])})}},systemStop:function(){if(L){L=!1;b.loopObject(H,
function(a){a.instance.destroy()});for(b.removeElement(m.pInstWrapper);m.pInstActive.hasChildNodes();)m.pInstActive.parentNode.insertBefore(m.pInstActive.firstChild,m.pInstActive);b.removeElement(m.pInstActive);b.loopObject(u,function(a){b.loopObject(a,function(a,d){b.removeEvent(d.element,a)})});m={};A={};D={};H={};I={};G={};u={};Q={};K={};R={};S={};w={};v={};J={};W=V=U=void 0;j=b.cloneObject(P);f.updateWindowNamespace();M=0}},updateWindowNamespace:function(a,c){var d={},e=function(a,b){n[s.root][a]=
b;n[s.root].prototype[a]=b};a&&c?e(a,c):(e(s.globalVars,p),e(s.settings,j),e(s.defaultSettings,P),e(s.user,w),e(s.json,R),e(s.lib,b),b.loopObject({systemStart:f.systemStart,systemStop:f.systemStop,updateSettings:f.updateSettings,loadImage:f.loadImage,unLoadImage:f.unLoadImage,checkForImages:f.checkForImages,promptRegister:f.promptRegister,promptLogin:f.promptLogin,promptLogout:f.promptLogout,promptAddTag:f.promptAddTag,promptSettings:f.promptSettings,promptOpenLightbox:f.promptOpenLightbox,changeTheme:f.changeTheme},
function(a,b){d[a]=b}),e(s.fn,d),e(s.images,D),e(s.nodes,H),e(s.tags,I),e(s.events,u),e(s.elements,Q))},onImageDimensionReady:function(a,c){function d(){var d={},f=function(){d.width=b.getWidth(a);d.height=b.getHeight(a);return 0!==d.width&&0!==d.height?!0:!1};!0===f()?c.call(a,d):b.runInterval(10,100,f,function(){c.call(a,d)})}a.complete?d():b.addEvent(a,k.load,d)},cacheImage:function(a){var c;a.pinUID||(c=b.randomID(10),D[c]={loaded:!1,image:a,offset:b.getCumulativeOffset(a)},a.pinUID=c)},checkForImages:function(a){function c(a){b.loopArray(a.getElementsByTagName(N),
function(a){f.cacheImage(a)})}L&&(j.loadAll?(a=a||l,b.isElement(a)||a===l?c(a):b.isArray(a)&&b.loopArray(a,function(a){c(a)})):(b.loopArray(b.getElementsByClassName(j.activeChildClass),function(a){f.cacheImage(a)}),b.loopArray(b.getElementsByClassName(j.activeParentClass),function(a){b.loopArray(a.getElementsByTagName(N),function(a){f.cacheImage(a)})}),0<j.loadImages.length&&b.loopArray(j.loadImages,function(a){f.cacheImage(a)})),b.loopObject(D,function(a){a.loaded||f.loadImage(a.image)}))},unLoadImage:function(a,
b){b=b||!1;f.manageUserInputImage(a,function(a){a.destroy(b)});delete D[a.pinUID]},loadImage:function(a){L&&(U++,f.verifyImageReference(a,function(a){var d,e=b.attribute(a,"src"),g=b.getFileExtension(e),h=!0;a.pinUID||f.cacheImage(a);d=b.hasProperty(J,a.pinUID)?J[a.pinUID]:new ia(a,a.pinUID);b.attribute(a,"loaded")===pa[1]?h=!1:!e||""===b.stripSpaces(e)?h=!1:b.inArray(j.allowFile.split("|"),g)?b.isElementIn(a,l)?m.pseudoSEO&&b.isElementIn(a,m.pseudoSEO)&&(h=!1):h=!1:h=!1;if(h)f.onImageDimensionReady(a,
function(e){if(!(e.width<j.nMinWidth||e.height<j.nMinHeight)){if(j.smartLoad){if(f.isHidden(this)){J[this.pinUID]=d;return}b.hasProperty(J,this.pinUID)&&delete J[this.pinUID]}V++;D[this.pinUID].loaded=!0;d.settings=b.cloneObject(j);j.custom&&(!b.isObjectEmpty(j.custom)&&b.hasProperty(j.custom,a.id))&&f.mergeStrictObjects(d.settings,j.custom[a.id]);delete d.settings.custom;d.init()}});else W++}))},mergeStrictObjects:function(a,c){b.loopObject(c,function(c,e){var g,h;b.hasProperty(a,c)&&(g=b.type(a[c]),
h=b.type(e),g===h&&(b.isObject(e)?b.isObjectEmpty(a[c])?a[c]=e:f.mergeStrictObjects(a[c],e):a[c]=e))})},updateSettings:function(a){f.mergeStrictObjects(j,a)},initKeyListener:function(){j.keyListener&&b.addEvent(l,k.keyup,function(a){var c=a.charCode||a.keyCode;b.hasProperty(A,c)&&b.loopObject(A[c],function(a){a(c)})})},newKeyListener:function(a,c,d){j.keyListener&&(b.isElement(c)&&(c=b.getGUID(c)),A[a]||(A[a]={}),c&&(A[a][c]=d))},removeKeyListener:function(a,c){j.keyListener&&A[a]&&(b.isElement(c)&&
(c=b.getGUID(c)),A[a][c]&&delete A[a][c],b.isObjectEmpty(A[a])&&delete A[a])},removeAllKeyListeners:function(a){j.keyListener&&b.loopObject(A,function(b,d){d[a]&&f.removeKeyListener(b,a)})},centerHorizontal:function(a){var c=b.getWidth(a);b.setStyle(a,"marginLeft","-"+String(c/2)+"px")},centerVertical:function(a){var c=b.getHeight(a);b.setStyle(a,"marginTop","-"+String(c/2)+"px")},openWindow:function(a,c){b.replaceHTML(m.pInstWindowBody,a);b.addClass(m.pInstWrapper,g.actionShowWin);f.centerVertical(m.pInstWindow);
f.newKeyListener(27,m.pInstWindow,function(){f.closeWindow()});c&&c.call(m.pInstWindow)},openPrivateWindow:function(a,c){var d=function(){f.openWindow(a,function(){var a=b.getElementsByClassName(g.windowUserName,this)[0];b.domAppend("span",a,"Logged in as: ");b.appendText(a,w[t.user.fullName]);b.click(b.getElementsByClassName(g.windowLogout,this)[0],function(){f.closeWindow();f.promptLogout()});c&&c.call(this)})};f.checkLogin(function(){d()},function(){f.promptLogin(function(){d()})})},closeWindow:function(){f.removeKeyListener(27,
m.pInstWindow);b.removeClass(m.pInstWrapper,g.actionShowWin);b.removeChildren(m.pInstWindowBody)},promptConfirm:function(a,c){f.openWindow(z.confirmPrompt,function(){var d=b.getElementsByClassName(g.promptAccept,this)[0],e=b.getElementsByClassName(g.promptDeny,this)[0];b.appendText(b.getElementsByClassName(g.promptMessage,this)[0],a);b.click(d,function(){f.waitButton(this,x.formWait);b.removeElement(e);c()});b.click(e,function(){f.closeWindow()})})},setWindowLink:function(a,c,d){d=d||"_self";b.click(a,
function(){n.open(c,d).focus()});b.attribute(a,"href",c)},openPopupWindow:function(a,c,d){var e=(n.screenTop||n.screenY||0)+(n.innerHeight||l.documentElement.clientHeight||0)/2-d/2,f=[];b.loopObject({toolbar:0,scrollbars:0,location:1,statusbar:0,menubar:0,resizable:1,width:c,height:d,left:Math.abs((n.screenLeft||n.screenX||0)+(n.innerWidth||l.documentElement.clientWidth||0)/2-c/2),top:Math.abs(e)},function(a,b){f[f.length]=a+"="+b});a=n.open(a,b.randomID(8),f.join(","));n.focus&&a.focus();return a},
updateUserInfo:function(a){null===a?b.loopObjectKeys(w,function(a){delete w[a]}):b.mergeObject(w,a)},checkLogin:function(a,c,d){var e=(new Date).getTime(),g=e-M,h=function(e){b.isObjectEmpty(e)?(O=!1,c&&c()):(O=!0,a&&a());d&&d()};0===M||6E4<g?(M=e,b.loadJSONP(r.names.checkLogin,function(a){f.updateUserInfo(a);h(a)})):h(w)},checkPermission:function(a){w[t.user.isOwner]?a&&a():f.openWindow(z.msgNoPermission)},waitButton:function(a,c){var d=f.deactivateEvents(a,[k.mouseover,k.mouseout]);b.isObjectEmpty(d)||
(a.oEventMemory=d);c&&(b.attribute(a,"orgtext",b.textContentRecursive(a)),b.textContentRecursive(a,c))},unwaitButton:function(a){b.textContentRecursive(a,b.attribute(a,"orgtext"));b.attribute(a,"orgtext",null);a.oEventMemory&&(f.activateEvents(a,a.oEventMemory),delete a.oEventMemory)},deactivateEvents:function(a,c){var d=b.getGUID(a),e={};b.loopArray(c,function(c){u[d]&&u[d][c]&&(e[c]=u[d][c].handler,b.removeEvent(a,c))});return e},activateEvents:function(a,c){b.loopObject(c,function(c,e){b.addEvent(a,
c,e)})},MouseBoundaryCrossing:function(a,c){a=a||n.event;var d=a.type,e,f;this.enteredLandmark=this.leftLandmark=this.inLandmark=!1;d===k.mouseout?(this.toElement=a.relatedTarget||a.toElement,this.fromElement=a.target||a.srcElement):d===k.mouseover&&(this.toElement=a.target||a.srcElement,this.fromElement=a.relatedTarget||a.fromElement);if(this.toElement&&this.fromElement){for(e=this.fromElement;b.isElement(e)&&e!==c;)e=e.parentNode;for(f=this.toElement;b.isElement(f)&&f!==c;)f=f.parentNode;e===c&&
f===c?this.inLandmark=!0:e===c&&f!==c?(this.leftLandmark=!0,this.inLandmark=d===k.mouseout):e!==c&&f===c&&(this.enteredLandmark=!0,this.inLandmark=d===k.mouseover)}},isHidden:function(a){var c=b.getCumulativeOffset(a),d=b.getWidth(a),e=b.getHeight(a),f=n.pageXOffset||l.documentElement.scrollLeft,g=n.pageYOffset||l.documentElement.scrollTop,h=n.innerWidth||l.documentElement.offsetWidth,j=n.innerHeight||l.documentElement.offsetHeight,k,m=a;do{var p;p=m;"fixed"===b.getStyle(p,"position").toLowerCase()?
(k=p,p=null):p=void 0;if(p)break;m=m.offsetParent}while(m);k&&(g=b.getCumulativeOffset(k),f=g.x,g=g.y);k=0>c.x-f+d?!0:!1;f=c.x>h+f?!0:!1;h=0>c.y-g+e?!0:!1;c=c.y>j+g?!0:!1;return k||f||h||c||0>d||0>e?!0:!b.isVisible(a)},getPosPercentage:function(a){var c=b.getEventTarget(a),d=b.getMousePosition(a),e=b.getCumulativeOffset(c);a=((d.x-e.x)/b.getWidth(c)).toFixed(10);c=((d.y-e.y)/b.getHeight(c)).toFixed(10);return{x:a,y:c}},manageKeywords:function(a){b.addEvent(a,k.change,function(){var a=this.value.replace($,
"").replace(aa,"").split(Y);this.value=b.arrayUnique(a).slice(0,10).join(", ").toLowerCase()})},loopFormFields:function(a,c){b.loopArray(a.elements,function(a){var b=a.nodeName.toLowerCase();if("input"===b||"textarea"===b||"select"===b)return c.call(a)})},manageFormSubmit:function(a,c,d,e,h){b.click(b.getElementsByClassName(g.formBtnSubmit,a)[0],function(){b.fireEvent(a,k.submit)});f.loopFormFields(a,function(){b.addEvent(this,k.focus,function(){b.addClass(this.parentNode,g.focus)});b.addEvent(this,
k.blur,function(){b.removeClass(this.parentNode,g.focus)})});f.formFocus(a);f.newKeyListener(13,a,function(){b.fireEvent(a,k.submit)});b.addEvent(a,k.submit,function(g){var j;b.stopBubble(g);g=f.getFormData(a);if(f.checkRequired(a,d)){if(h&&(j=h.call(a,g)))return f.displayFormError(a,j),!1;f.disableForm(a);b.loadJSONP(c,g,function(b){f.enableForm(a);e.call(a,b)})}})},getFormData:function(a){var c={};b.loopArray(a.elements,function(a){if("$"===a.value||a.value===X)a.value="";a.name&&a.value&&(c[a.name]=
a.value)});return c},displayFormError:function(a,c){var d=b.getElementsByClassName(g.formError,a)[0];c?(b.replaceHTML(d,c),b.loopArray(a.getElementsByTagName("input"),function(a){"password"===a.type&&(a.value="")}),f.formFocus(a)):b.removeChildren(d)},formFocus:function(a){f.loopFormFields(a,function(){if(!this.value)return this.focus(),null})},checkRequired:function(a,c){var d=0,e=function(a){var c=b.getParentByClassName(a,g.formLabel);c||(c=b.getParentByClassName(a,g.formLabelSm));!a.value||""===
a.value?(d++,c&&b.addClass(c,g.formErrorRow)):c&&b.removeClass(c,g.formErrorRow)};1===c.length?"*"===c[0]?f.loopFormFields(a,function(){e(this)}):e(a.elements[c[0]]):0<c.length&&b.loopArray(c,function(b){e(a.elements[b])});if(0<d)return f.displayFormError(a,x.missingReqInput),!1;f.displayFormError(a,null);return!0},enableFormElement:function(a){b.attribute(a,"disabled",null);"input"===a.nodeName.toLowerCase()&&b.attribute(a,"readonly",null);return a},disableFormElement:function(a){b.attribute(a,"disabled",
"disabled");"input"===a.nodeName.toLowerCase()&&b.attribute(a,"readonly","readonly");return a},disableForm:function(a){var c=b.getElementsByClassName(g.formBtnSubmit,a)[0];b.loopArray(a.elements,function(a){f.disableFormElement(a)});c&&f.waitButton(c,x.formWait)},enableForm:function(a){var c=b.getElementsByClassName(g.formBtnSubmit,a)[0];b.loopArray(a.elements,function(a){f.enableFormElement(a)});c&&f.unwaitButton(c)},manageTagSuggestionList:function(a){var c=b.domAppend("div",a,{"class":g.formDropDownDiv}),
d=a.elements.strTagName,e=b.getCumulativeOffset(d),f=b.getCumulativeOffset(c.parentNode),h=function(e){clearTimeout(c.timeout);e?c.timeout=setTimeout(function(){b.removeChildren(c);b.appendText(c,x.loading);b.show(c);b.loadJSONP(r.names.getTagSugg,{strChars:e},function(e){b.removeChildren(c);b.hasClass(d.parentNode,g.focus)&&(null===e?b.appendText(c,x.timeoutError):b.isUndefined(e)?b.textContent(c,x.noResults):b.loopArray(e,function(e){var f,h;h={};h.weblink=e[t.tags.webLink];h.keywords=e[t.tags.keywords].join(", ");
f=b.domAppend("span",c,h);h={};h["class"]=g.iconLabel;b.domAppend("span",f,h);b.appendText(f,e[t.tags.name]);b.addEvent(f,k.mousedown,function(a){b.stopBubble(a)});b.click(f,function(){a.elements.strTagName.value=b.textContent(this);a.elements.strWebLink.value=b.attribute(this,"weblink");a.elements.strKeywords.value=b.attribute(this,"keywords");d.blur()},!0)}))})},300):(b.removeChildren(c),b.hide(c))};c.style.left=String(e.x-f.x-9)+"px";c.style.top=String(e.y-f.y+33)+"px";b.addEvent(d,k.focus,function(){b.addClass(this.parentNode,
g.focus);this.value&&h(this.value)});b.addEvent(d,k.blur,function(){b.removeClass(this.parentNode,g.focus);b.removeChildren(c);b.hide(c)});b.addEvent(d,k.keyup,function(){h(this.value)});b.hide(c)},currencyFormat:function(a){var b,d;a=a.toString().replace(T,"");a=isNaN(a)?"0":a;b=0>parseFloat(a)?"-":"";a=Math.floor(100*Math.abs(a)+0.50000000001);d=String(a%100);2>d.length&&(d="0"+d);a=Math.floor(a/100);var e;a=a.toString();for(e=0;e<Math.floor((a.length-(1+e))/3);e++)a=a.substring(0,a.length-(4*e+
3))+","+a.substring(a.length-(4*e+3));return b+"$"+a+"."+d},urlFormat:function(a){var c=b.parseUrl(a),d=["http","https"];if(!c.protocol||!b.inArray(d,c.protocol))a=X+c.host+c.relative;return a},validWebUrl:function(a){b.addEvent(a,k.change,function(){this.value=f.urlFormat(this.value)});""===a.value?a.value=X:b.fireEvent(a,k.change)},getCanvasContext:function(a,c){b.isUndefined(n[s.vmlCanvas])||n[s.vmlCanvas].initElement(a);return c?a.getContext(c):!!a.getContext},getStylePrefixes:function(a){var c=
[b.camelize(a)];b.loopArray(["webkit","moz","o","ms","khtml"],function(d){c[c.length]=b.camelize("-"+d+"-"+a)});return c},checkSupport:function(){var a=l.createElement("div"),c=l.createElement("canvas"),d;a.innerHTML='<span style="float:left;opacity:.55;"></span>';d=a.getElementsByTagName("span")[0];v.cssFloat=d.style.cssFloat?"cssFloat":"styleFloat";v.opacity=ga.test(d.style.opacity);v.propertychange=b.hasProperty(l,"onpropertychange")?"propertychange":"DOMAttrModified";v.canvas=f.getCanvasContext(c);
c=a.style.color;f.attempt(function(){a.style.color="rgba(0, 0, 0, 0.5)"});v.rgba=a.style.color!==c;v.boxShadow=!1;b.loopArray(f.getStylePrefixes("box-shadow"),function(c){if(!b.isUndefined(a.style[c]))return v.boxShadow=!0,null});v.borderRadius=!1;b.loopArray(f.getStylePrefixes("border-radius"),function(c){if(!b.isUndefined(a.style[c]))return v.borderRadius=!0,null})},setFluidWidth:function(a){var c=b.getWidth(a);b.setWidth(a,"auto");b.setStyle(a,"float","left");b.attribute(a,"fluidwidth",b.getWidth(a));
b.setWidth(a,c);b.setStyle(a,"float","none")},isValidEmail:function(a){var b=a.lastIndexOf("@"),d=a.lastIndexOf(".");return 1>b||b===a.length-1||64<b||255<a.length-b?!1:d>b+1&&d<a.length-1||"["===a.charAt(b+1)&&"]"===a.charAt(a.length-1)?!0:!1},manageBackToLogin:function(a,c){b.click(b.getElementsByClassName(g.formOption_backToLogin,a)[0],function(){f.promptLogin(c)})},manageRegistration:function(a,c){b.click(b.getElementsByClassName(g.formOption_register,a)[0],function(){f.promptRegister(c)})},manageForgotPass:function(a,
c){b.click(b.getElementsByClassName(g.formOption_forgotPass,a)[0],function(){f.openWindow(z.formForgot,function(){var a=l.forms.PIN_formForgot;f.manageBackToLogin(a,c);f.manageFormSubmit(a,r.names.forgot,["*"],function(a){a?f.displayFormError(this,a):(f.openWindow(z.msgForgot),O&&f.promptLogout(),c&&c())})})})},promptRegister:function(a){f.openWindow(z.formRegister,function(){var c=l.forms.PIN_registerForm;f.manageBackToLogin(c,a);c.elements.strWebURL.value=b.parseUrl(ma).host.split(".").slice(-2).join(".");
f.validWebUrl(c.elements.strWebURL);f.manageFormSubmit(c,r.names.register,["*"],function(c){b.isString(c)?f.displayFormError(this,c):b.isUndefined(c)&&(f.openWindow(z.msgRegistered),a&&a(c))},function(a){if(!f.isValidEmail(a.strUsername))return this.elements.strUsername.value="",x.invalidEmail})})},promptLogin:function(a){f.openWindow(z.formLogin,function(){var c=l.forms.PIN_loginForm;f.manageForgotPass(c,a);f.manageRegistration(c,a);f.manageFormSubmit(c,r.names.login,["*"],function(c){b.isString(c)?
f.displayFormError(this,c):b.isObject(c)&&(O=!0,M=0,f.updateUserInfo(c),f.methodSessionChange(),f.closeWindow(),j.onLogin&&j.onLogin.call(n[s.root],c),a&&a())},function(a){if(!f.isValidEmail(a.strUsername))return this.elements.strUsername.value="",x.invalidEmail})})},promptLogout:function(){b.loadJSONP(r.names.logout);O=!1;M=0;f.updateUserInfo(null);f.methodSessionChange();j.onLogout&&j.onLogout.call(n[s.root])},methodSessionChange:function(a){var c=b.getParamsFromObject(w),d=function(a){a!==la&&
this.ui.destroy();this.updateNode(!0);this.ui.check()};a?d.call(a,c):b.loopObject(H,function(a){d.call(a.instance,c)});la=c},findImageByString:function(a){var c,d=l.getElementById(a);d?c=d:b.loopArray(l.getElementsByTagName(N),function(d){if(b.attribute(d,"src")===a||d.src===a)c=d});return c},verifyImageReference:function(a,c){b.isString(a)&&(a=f.findImageByString(a));a&&b.isElement(a)&&c&&c(a)},getInstanceByImage:function(a){var c=b.getGUID(a),d;c&&b.loopObject(H,function(a,b){b.imgGUID===c&&(d=
a)});return d?H[d].instance:void 0},manageUserInputImage:function(a,b){f.verifyImageReference(a,function(a){(a=f.getInstanceByImage(a))&&b&&b(a)})},getTagGuidObject:function(a){var c={tagGUID:b.attribute(a,"taguid")};c.tagGUID||(delete c.tagGUID,c.tagMultiGUID=b.attribute(a,"taguids"));c.tagMultiGUID||delete c.tagMultiGUID;return b.isObjectEmpty(c)?void 0:c},promptAddTag:function(a){var b=function(){this.startTaggingMode(this.methodAddNewTag)};f.manageUserInputImage(a,function(a){f.checkLogin(function(){b.call(a)},
function(){f.promptLogin(function(){b.call(a)})})})},promptRepositionTags:function(a){f.manageUserInputImage(a,function(a){f.checkLogin(function(){a.startTagRepositionMode()},function(){f.promptLogin(function(){a.startTagRepositionMode()})})})},promptRemoveTags:function(a){f.manageUserInputImage(a,function(a){f.checkLogin(function(){a.startTagRemovalMode()},function(){f.promptLogin(function(){a.startTagRemovalMode()})})})},promptOpenLightbox:function(a){var c,d,e,h,j,k,l,p=0,q=0,r=[],s=function(a){a=
h.children[a];b.loopArray(h.children,b.hide);if("img"===a.nodeName.toLowerCase())f.onImageDimensionReady(a,function(){b.show(this);f.centerVertical(e);f.centerHorizontal(e);f.loadImage(this);r.push(H[this.pinUID])});else b.show(a),f.centerVertical(e),f.centerHorizontal(e)},t=function(){p-=1;0>p&&(p=l);s(p)},u=function(){p+=1;p>l&&(p=0);s(p)},v=function(){b.loopArray(r,function(a){a.instance.destroy()});r=[];b.removeElement(c)};(d=b.getElementsByClassName(g.lightboxOverlay)[0])&&b.fireEvent(d,"click");
b.isObjectEmpty(D)||(c=b.domAppend("div",m.pInstActive,{"class":g.lightbox}),d=b.domAppend("div",c,{"class":g.lightboxOverlay}),e=b.domAppend("div",c,{"class":g.lightboxWindow}),h=b.domAppend("div",e,{"class":g.lightboxImageHolder}),j=b.domAppend("div",e,{"class":g.lightboxNav+" "+g.lightboxShowLeft}),k=b.domAppend("div",e,{"class":g.lightboxNav+" "+g.lightboxShowRight}),b.domAppend("span",j,{"class":g.lightboxNavIcon}),b.domAppend("span",k,{"class":g.lightboxNavIcon}),b.click(d,v),b.click(j,t),b.click(k,
u),f.newKeyListener(37,c,t),f.newKeyListener(39,c,u),b.loopObject(D,function(c,d){c===a.pinUID&&(p=q);d.image.src!==n.location.href&&(b.domAppend(N,h,{"class":g.lightboxImage,src:d.image.src}),q+=1)}),l=q-1,s(p))},promptSettings:function(a){f.openPrivateWindow(z.formSettings,function(){var c=l.forms.PIN_formSettings;b.click(c.elements.btnRepositionTags,function(){f.promptRepositionTags(a);f.closeWindow()});b.click(c.elements.btnRemoveTags,function(){f.promptRemoveTags(a);f.closeWindow()});b.click(c.elements.btnOpenLightbox,
function(){f.closeWindow();f.promptOpenLightbox(a)});G[a.src]&&G[a.src][1]?(b.show(c.elements.btnRepositionTags),b.show(c.elements.btnRemoveTags)):(b.hide(c.elements.btnRepositionTags),b.hide(c.elements.btnRemoveTags))})},startDragging:function(a){b.addEvent(l,k.mousemove,function(c){var d=b.getMousePosition(c),e=b.getCumulativeOffset(a.parentNode);c=d.x-e.x;var d=d.y-e.y,e=b.getWidth(a.parentNode),f=b.getHeight(a.parentNode),g={};10>c?c=10:c>e-10-1&&(c=e-10-1);10>d?d=10:d>f-10-1&&(d=f-10-1);b.attribute(a,
"posx",(c/e).toFixed(10));b.attribute(a,"posy",(d/f).toFixed(10));g.left=c;g.top=d;b.setStyles(a,g)})},stopDragging:function(){b.removeEvent(l,k.mousemove)},getLocalStorage:function(a){var b;if(j.allowLocalStorage&&n.localStorage&&n.JSON)if(b=localStorage.getItem(a).split("_"),a=b.shift(),b=b.join("_"),"boolean"===a)b="true"===b;else if("number"===a)b=parseFloat(b);else if("date"===a)b=new Date(b);else if("array"===a||"object"===a)b=JSON.parse(b);return b},setLocalStorage:function(a,c){var d;if(j.allowLocalStorage&&
(n.localStorage&&n.JSON)&&(d=b.type(c),!("null"===d||"undefined"===d||"element"===d||"function"===d))){if("boolean"===d||"number"===d||"date"===d)c=c.toString();else if("array"===d||"object"===d)c=JSON.stringify(c);localStorage.setItem(a,d+"_"+c)}},manageTheme:function(a){var c,d;a&&""!==a&&(d=parseInt(a.split(".")[0],10),b.getStyle(m.pInstWrapper,"zIndex")!==d&&(c={},c.href=r.paths.themes+a,c.rel="stylesheet",c.type="text/css",b.domAppend("link",l.getElementsByTagName("head")[0],c)),b.addClass(m.pInstActive,
"PIN_"+d))},changeTheme:function(a){b.loopObject(H,function(a){a.instance.destroy()});f.manageTheme(a);f.checkForImages()},attempt:function(a){try{a.call()}catch(b){}}};n[s.root]=ja})(window);